version: "3.9"
services:
 useritem-api-service:
  image: wobr53/apidev-example-db
  ports:
    - "8000:8000"
  volumes:
    - sqlite_useritems_volume:/code/sqlitedb

volumes:
  sqlite_useritems_volume: